Properties:
  domain: caninecommons.cancer.gov

  plurals:
    program: programs
    study: studies
    study_site: study_sites
    study_arm: study_arms
    agent: agents
    cohort: cohorts
    case: cases
    demographic: demographics
    cycle: cycles
    visit: visits
    principal_investigator: principal_investigators
    diagnosis: diagnoses
    enrollment: enrollments
    prior_therapy: prior_therapies
    prior_surgery: prior_surgeries
    agent_administration: agent_administrations
    sample: samples
    evaluation: evaluations
    assay: assays
    file: files
    image: images
    physical_exam: physical_exams
    vital_signs: vital_signs
    lab_exam: lab_exams
    adverse_event: adverse_events
    disease_extent: disease_extents
    follow_up: follow_ups
    off_study: off_studies
    off_treatment: off_treatments

  type_mapping:
    string: String
    number: Float
    integer: Int
    boolean: Boolean
    array: Array
    object: Object
    datetime: DateTime
    date: Date
    TBD: String

  id_fields:
    program: program_acronym
    study: clinical_study_designation
    study_arm: arm
    cohort: cohort_description
    case: case_id
    #enrollment: enrollment_id
    visit: visit_id
    #diagnosis: diagnosis_id
    sample: sample_id
    file: uuid

  visit_date_in_nodes:
    vital_signs: date_of_vital_signs
    physical_exam: date_of_examination
    disease_extent: date_of_evaluation

